<!DOCTYPE html>

<html lang="en-us">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no"/>

    <title>Hire Me (as a Data Scientist!), Part I | David John Baker</title>
    
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#FF3DB4">
    <meta name="theme-color" content="#ffffff">

    
    
    
    <link rel="stylesheet" href="https://example.com/css/main.min.14b4423f0d8056e151aa84e4088f5298a8f910509beca2cb87d2fdd00c8ff4e5.css"/>

    
    
    

    
    
 
    </head>

    <body>
        
<nav>
  <header>
    <div class="site-title">
        <a href="/">David John Baker</a>
    </div>  
</header>

  <div class="nav-menu">
  
    <a class="color-link nav-link" href="/about/">About</a>
  
    <a class="color-link nav-link" href="/archives/">Blog</a>
  
    <a class="color-link nav-link" href="/academic/">Academic</a>
  
    <a class="color-link nav-link" href="/industry/">Industry</a>
  
    <a class="color-link nav-link" href="/teaching/">Teaching</a>
  
    <a class="color-link nav-link" href="/service/">Service</a>
  
    <a class="color-link nav-link" href="/tags/">Tags</a>
  
  <a class="color-link nav-link" href="https://example.com/index.xml" target="_blank" rel="noopener" type="application/rss+xml">RSS</a>
</div>
<footer class="footer">
	<div class="social-icons">
        
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Email">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M25.2794292,5.59128519 L14,16.8707144 L2.72057081,5.59128519 C3.06733103,5.30237414 3.51336915,5.12857603 4,5.12857603 L24,5.12857603 C24.4866308,5.12857603 24.932669,5.30237414 25.2794292,5.59128519 Z M25.9956978,6.99633695 C25.998551,7.04004843 26,7.08414302 26,7.12857603 L26,20.871424 C26,21.0798433 25.9681197,21.2808166 25.9089697,21.4697335 L18.7156355,14.2763993 L25.9956978,6.99633695 Z M24.9498374,22.6319215 C24.6672737,22.7846939 24.3437653,22.871424 24,22.871424 L4,22.871424 C3.5268522,22.871424 3.09207889,22.7071233 2.74962118,22.432463 L10.0950247,15.0870594 L13.9848068,18.9768415 L14.1878486,18.7737996 L14.2030419,18.7889929 L17.6549753,15.3370594 L24.9498374,22.6319215 Z M2.00810114,21.0526627 C2.00273908,20.9929669 2,20.9325153 2,20.871424 L2,7.12857603 C2,7.08414302 2.00144896,7.04004843 2.00430222,6.99633695 L9.03436454,14.0263993 L2.00810114,21.0526627 Z"></path>
        </svg>
    </a>
    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Twitter">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M8.991284,24.971612 C19.180436,24.971612 24.752372,16.530224 24.752372,9.210524 C24.752372,8.970656 24.747512,8.731868 24.736496,8.494376 C25.818008,7.712564 26.758256,6.737 27.5,5.62622 C26.507372,6.067076 25.439252,6.364292 24.318752,6.498212 C25.462472,5.812628 26.340512,4.727444 26.754584,3.434036 C25.684088,4.068536 24.499004,4.53002 23.23724,4.778528 C22.226468,3.701876 20.786828,3.028388 19.193828,3.028388 C16.134404,3.028388 13.653536,5.509256 13.653536,8.567492 C13.653536,9.0023 13.702244,9.424904 13.797176,9.830552 C9.19346,9.599108 5.11106,7.39472 2.3792,4.04294 C1.903028,4.861364 1.629032,5.812628 1.629032,6.827072 C1.629032,8.74904 2.606972,10.445612 4.094024,11.438132 C3.185528,11.41016 2.331788,11.160464 1.585184,10.745096 C1.583888,10.768208 1.583888,10.791428 1.583888,10.815728 C1.583888,13.49888 3.493652,15.738584 6.028088,16.246508 C5.562932,16.373084 5.07326,16.44134 4.56782,16.44134 C4.210988,16.44134 3.863876,16.406024 3.526484,16.34144 C4.231724,18.542264 6.276596,20.143796 8.701412,20.18894 C6.805148,21.674696 4.416836,22.56008 1.821488,22.56008 C1.374476,22.56008 0.93362,22.534592 0.5,22.4834 C2.951708,24.054476 5.862524,24.971612 8.991284,24.971612"></path>
        </svg>
    </a>
    

    

    

    

    

    

    

    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="LinkedIn">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M2,3.654102 C2,2.69908141 2.79442509,1.92397846 3.77383592,1.92397846 L24.2261641,1.92397846 C25.2058917,1.92397846 26,2.69908141 26,3.654102 L26,24.3462148 C26,25.3015521 25.2058917,26.0760215 24.2261641,26.0760215 L3.77383592,26.0760215 C2.79442509,26.0760215 2,25.3015521 2,24.3465315 L2,3.65378524 L2,3.654102 Z M9.27526132,22.1415901 L9.27526132,11.2356668 L5.65030092,11.2356668 L5.65030092,22.1415901 L9.27557808,22.1415901 L9.27526132,22.1415901 Z M7.46341463,9.74691162 C8.72727273,9.74691162 9.51409566,8.90940767 9.51409566,7.86284447 C9.49033893,6.79252455 8.72727273,5.97846056 7.48748812,5.97846056 C6.24675325,5.97846056 5.43649034,6.79252455 5.43649034,7.86284447 C5.43649034,8.90940767 6.22299652,9.74691162 7.4396579,9.74691162 L7.46309788,9.74691162 L7.46341463,9.74691162 Z M11.2815965,22.1415901 L14.9062401,22.1415901 L14.9062401,16.0519481 C14.9062401,15.7263225 14.9299968,15.4000634 15.0256573,15.1675641 C15.2876148,14.5159962 15.8840672,13.8416218 16.8856509,13.8416218 C18.1970225,13.8416218 18.7218879,14.8416218 18.7218879,16.3078872 L18.7218879,22.1415901 L22.3465315,22.1415901 L22.3465315,15.8885017 C22.3465315,12.5388027 20.5584416,10.9800443 18.1735825,10.9800443 C16.2182452,10.9800443 15.3595185,12.072854 14.8824834,12.8172315 L14.9065569,12.8172315 L14.9065569,11.2359835 L11.2819132,11.2359835 C11.3291099,12.2591067 11.2815965,22.1419069 11.2815965,22.1419069 L11.2815965,22.1415901 Z"></path>
        </svg>
    </a>
    

    

    

    

    

    

    

    
    
    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="GitHub">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M13.9988029,1.32087331 C6.82105037,1.32087331 1,7.14112562 1,14.3212723 C1,20.0649109 4.72454649,24.9370678 9.89038951,26.6560892 C10.5408085,26.7757983 10.7778323,26.374374 10.7778323,26.0296121 C10.7778323,25.7215609 10.7666595,24.9035493 10.760275,23.8189856 C7.14426471,24.6042767 6.38131925,22.0760223 6.38131925,22.0760223 C5.78995672,20.5740732 4.93762853,20.1742451 4.93762853,20.1742451 C3.75729765,19.3682044 5.02701126,19.3841656 5.02701126,19.3841656 C6.33183953,19.4759425 7.01817121,20.7241085 7.01817121,20.7241085 C8.17775254,22.7104801 10.0611744,22.1366749 10.8017741,21.8038838 C10.919887,20.9643246 11.2558703,20.3913175 11.6269683,20.066507 C8.74038491,19.7385043 5.70536235,18.6228163 5.70536235,13.6413251 C5.70536235,12.2223743 6.21213051,11.0611968 7.04370914,10.1530044 C6.90963504,9.82420367 6.46351945,8.50181809 7.17139875,6.71256734 C7.17139875,6.71256734 8.26234691,6.36301702 10.7459099,8.04532771 C11.78259,7.75642995 12.8950858,7.61277914 14.000399,7.60719272 C15.1049142,7.61277914 16.2166119,7.75642995 17.2548881,8.04532771 C19.736855,6.36301702 20.8262071,6.71256734 20.8262071,6.71256734 C21.5356825,8.50181809 21.0895669,9.82420367 20.9562909,10.1530044 C21.7894656,11.0611968 22.2922435,12.2223743 22.2922435,13.6413251 C22.2922435,18.6355852 19.2524325,19.734514 16.3570705,20.0561322 C16.8231376,20.4575564 17.2389269,21.2508282 17.2389269,22.4638795 C17.2389269,24.2012564 17.2229657,25.603448 17.2229657,26.0296121 C17.2229657,26.3775663 17.4575954,26.7821827 18.116793,26.6552912 C23.2786458,24.9322794 27,20.0633148 27,14.3212723 C27,7.14112562 21.1789496,1.32087331 13.9988029,1.32087331"></path>
        </svg>
    </a>
    

    
    
    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Google Scholar">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
             <path d="M15.7399177,5.48151786 C15.149924,4.82272859 14.4663239,4.49480724 13.6933878,4.49480724 C12.8185607,4.49480724 12.1471312,4.80966127 11.6791845,5.43796013 C11.2112379,6.06433732 10.9771365,6.82326666 10.9771365,7.71483354 C10.9771365,8.47423262 11.1052474,9.24733956 11.3616402,10.035649 C11.6170934,10.8236168 12.0350768,11.5270314 12.6210136,12.1470458 C13.2049434,12.7685974 13.8844439,13.0787968 14.6564833,13.0787968 C15.5171327,13.0787968 16.189459,12.7903763 16.671626,12.2137916 C17.1517432,11.6379755 17.3927199,10.9111166 17.3927199,10.035649 C17.3927199,9.29000051 17.2655484,8.50924961 17.0102233,7.69296927 C16.7561365,6.87562134 16.3319184,6.13812924 15.739875,5.48156056 L15.7399177,5.48151786 Z M24.3072528,4.96950105 L24.3072528,13.3462071 C24.3072528,13.7339989 23.9898792,14.0515006 23.6019592,14.0515006 L23.3422783,14.0515006 C22.9543156,14.0515006 22.6369848,13.7341271 22.6369848,13.3462071 L22.6369848,4.96950105 C22.6369848,4.62513879 22.5869788,4.33765779 23.068249,4.27714671 L23.068249,3.16262405 L19.3634081,6.20120253 C19.4061972,6.28058863 19.446851,6.33132057 19.4854124,6.39789556 C19.8110278,6.97418137 19.9768461,7.69087679 19.9768461,8.56681414 C19.9768461,9.23824368 19.8649625,9.84134739 19.638078,10.3740328 C19.4122611,10.9065473 19.1375912,11.3415267 18.817143,11.6765369 C18.496652,12.0127855 18.1752643,12.3201237 17.8538766,12.5967152 C17.5324462,12.8739047 17.2577763,13.162923 17.0328135,13.4629589 C16.8060571,13.7620125 16.6932767,14.0712297 16.6932767,14.3917206 C16.6932767,14.7126813 16.8397076,15.0387237 17.1317151,15.3673283 C17.4226551,15.6968724 17.7805972,16.0162103 18.2038758,16.3317049 C18.6279231,16.6450216 19.0510736,16.9928002 19.4743522,17.3712399 C19.8985703,17.74921 20.2545052,18.2354765 20.5454452,18.8259399 C20.8385631,19.4186239 20.9848231,20.071093 20.9848231,20.7882582 C20.9848231,21.7343577 20.7435475,22.5887297 20.2626616,23.3491963 C19.7802812,24.1064175 19.1518542,24.7106315 18.3796867,25.1537246 C17.6054695,25.599807 16.777531,25.9355858 15.8945476,26.1623422 C15.0097279,26.3870488 14.1317408,26.5 13.2548639,26.5 C12.7014246,26.5 12.1429889,26.4573818 11.5814359,26.3697112 C11.0178757,26.2822114 10.4532907,26.1276668 9.8847343,25.9098782 C9.31502485,25.6906377 8.81052389,25.4214338 8.37319577,25.0981672 C7.93475736,24.778146 7.58181166,24.3652016 7.3111559,23.862238 C7.04054285,23.3591036 6.90615445,22.7936645 6.90615445,22.1655364 C6.90615445,21.4203577 7.1136515,20.7291563 7.52975591,20.0847582 C7.94586031,19.4451002 8.49707907,18.9108775 9.18272893,18.487727 C10.3789864,17.7434877 12.2558547,17.2836547 14.8102164,17.1098936 C14.2262867,16.3799173 13.9333396,15.6928582 13.9333396,15.0498693 C13.9333396,14.6841125 14.0289531,14.2920503 14.218173,13.8687717 C13.9130554,13.9113899 13.5987992,13.9355175 13.2781801,13.9355175 C11.9059836,13.9355175 10.7472627,13.4894351 9.80628769,12.5911638 C8.86535538,11.6944724 8.39535897,10.5719642 8.39535897,9.21488479 C8.39535897,9.07298054 8.39941581,8.94802965 8.40970739,8.8095417 L2.83316537,8.8095417 L11.2417283,1.5 L25.1668346,1.5 L23.87996,2.50451805 L23.87996,4.27748834 C24.3577712,4.3388962 24.3072955,4.62607827 24.3072955,4.96950105 L24.3072528,4.96950105 Z M15.8172967,17.9839947 C15.6566455,17.9549562 15.430914,17.9386434 15.1399313,17.9386434 C14.512273,17.9386434 13.8947782,17.9941154 13.2885571,18.1048887 C12.6822934,18.2126727 12.084186,18.3947184 11.4941496,18.6515809 C10.9019353,18.906906 10.423996,19.2823566 10.0597766,19.7787865 C9.69355004,20.274576 9.51150436,20.858463 9.51150436,21.5303623 C9.51150436,22.1706609 9.67215551,22.7419077 9.99371402,23.2394479 C10.3142049,23.7338281 10.7373127,24.1208513 11.2632509,24.3980408 C11.7891891,24.6756999 12.3405787,24.8854176 12.916224,25.0231795 C13.4929795,25.1600875 14.0799412,25.2311463 14.6780913,25.2311463 C15.8610679,25.2311463 16.8794647,24.9647609 17.7338794,24.4320756 C18.5863724,23.899561 19.0135798,23.0772595 19.0135798,21.9672634 C19.0135798,21.7338025 18.9810823,21.5040141 18.916856,21.2796064 C18.8498112,21.0527219 18.7835352,20.8585057 18.7185829,20.6972567 C18.6534171,20.5389543 18.529363,20.3483679 18.3462498,20.1286576 C18.1642041,19.9083067 18.0248194,19.7455631 17.9310848,19.6372239 C17.8354714,19.5253403 17.6565431,19.3656714 17.3929761,19.1545445 C17.131587,18.9425209 16.9647012,18.8103104 16.8904822,18.7614574 C16.8172027,18.7100422 16.6270434,18.5711699 16.3207728,18.3458227 C16.0147157,18.1186393 15.8468903,17.9981723 15.8173394,17.983952 L15.8172967,17.9839947 Z"></path>
        </svg>
    </a>
    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Orcid">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M27,14 C27,21.1804687 21.1804687,27 14,27 C6.81953125,27 1,21.1804687 1,14 C1,6.81953125 6.81953125,1 14,1 C21.1804687,1 27,6.81953125 27,14 Z M9.76484375,19.9109375 L9.76484375,13.9492188 L9.76484375,9.03359375 L8.20078125,9.03359375 L8.20078125,19.9109375 L9.76484375,19.9109375 Z M12.0601563,9.03359375 L12.0601563,19.9210938 L16.3054688,19.9210938 C19.890625,19.9210938 22.0742188,17.2703125 22.0742188,14.4773437 C22.0742188,11.9078125 20.3070313,9.03359375 16.2851563,9.03359375 L12.0601563,9.03359375 Z M13.6242188,18.509375 L13.6242188,10.4453125 L16.03125,10.4453125 C19.078125,10.4453125 20.4695313,12.29375 20.4695313,14.4773437 C20.4695313,15.8179688 19.6570313,18.509375 16.1125,18.509375 L13.6242188,18.509375 Z M10.0085938,6.76875 C10.0085938,6.21015625 9.5515625,5.74296875 8.9828125,5.74296875 C8.4140625,5.74296875 7.95703125,6.2 7.95703125,6.76875 C7.95703125,7.32734375 8.4140625,7.79453125 8.9828125,7.79453125 C9.5515625,7.79453125 10.0085938,7.32734375 10.0085938,6.76875 Z"></path>
        </svg>
    </a>
    

    

</div>




	<p><a href="https://github.com/kimcc/hugo-theme-noteworthy" target="_blank" rel="noopener">Noteworthy theme</a></p>
	<p><a href="https://gohugo.io" target="_blank" rel="noopener">Built with Hugo</a></p>

	<script src="https://example.com/js/main.min.c1aee25a817e9beb1f9c4afd9d62311227a7f5e46720e404dc1dda97281f47f2.js" integrity="sha256-wa7iWoF+m+sfnEr9nWIxEien9eRnIOQE3B3alygfR/I=" crossorigin="anonymous"></script>
</footer>
</nav>

        <div id="content" class="content-container">
        

<h1 class="post-title">Hire Me (as a Data Scientist!), Part I</h1>
    
    <time>January 13, 2018</time>
    
    <div>
        <p>
        


<div id="background" class="section level2">
<h2>Background</h2>
<p>I read <a href="https://medium.com/">Medium</a> blog posts on “How to Become a Data Scientist” more often than I care to admit.
Much of this comes from a fear that after doing all this work on the PhD and then hitting the Music Theory job market, I won’t fit the mold of the kind of theorist most schools want to hire.
Not coming from <a href="https://pushpullfork.com/music-theory-job-market/">one of five schools that seem to have a monopoly on the tenure track jobs</a> can be a bit discouraging, but I also won’t deny that having a non-academic job with a regular 9-5 schedule and a <a href="https://www.glassdoor.com/Salaries/data-scientist-salary-SRCH_KO0,14.htm">decent salary</a> is pretty tempting after spending the vast majority of my twenties in school.
And even if I don’t go on over to industry after the PhD, I’ll probably always be looking for a bit more work in summer.</p>
<p>On top of all of that, I believe that skills that are acquired in a PhD (especially if you do computational musicology and music cognition!) are very transferable to most jobs, and it’s just a matter of being a bit more pro-active in promoting myself that might help me one day land a stable, non-academic job.</p>
<p>That said, one tweet I saw last week by <a href="https://twitter.com/kierisi">Jesse Meagan</a> linked to this really interesting Linked-In
post by <a href="https://twitter.com/tanyacash21">Tanya Cashorali</a> that purported to have a <a href="https://www.linkedin.com/pulse/how-hire-test-data-skills-one-size-fits-all-interview-tanya-cashorali/">one size fits all data-science interview process</a> which has candidates take home a big dataset with a bunch of beer reviews and answer four very broad questions.
Considering myself an aficionado of How-To-Become-a-Data Scientist articles, this of course caught my eye.</p>
<p>After reading the article, I figured why not give it a go?
It’s the start of the semester, I’m basically ABD, need more of a portfolio beyond <a href="www.github.com/davidjohnbaker1">my github</a>, and I have nothing to do with my Saturday morning.
Why not see what I can produce in 4 or 5 hours?
At the very least I’ll hopefully just have something to point to if a future employer wants to see how I think through data-science problems.</p>
<p>And if anyone is reading this that does have comments on my code or thought process… please let me know what you think on <a href="www.twitter.com/DavidJohnBaker">Twitter</a>!
I’d love some feedback!</p>
</div>
<div id="exploring-the-dataset" class="section level2">
<h2>Exploring the Dataset</h2>
<p>The first thing I did was to grab this dataset which you can get <a href="https://s3.amazonaws.com/demo-datasets/beer_reviews.tar.gz?lipi=urn%3Ali%3Apage%3Ad_flagship3_pulse_read%3BDqDjqRycTlq5seB4xN3ocA%3D%3D">here</a> and then I set up my R script with a few of my favorite packages (again, big love to Ben at <a href="https://gormanalysis.com/">GormAnalysis</a> for helping me learn <a href="https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html">data.table</a>).</p>
<pre class="r"><code>#=====================================================================================#
# Beer Script
#=====================================================================================#
# Library
library(ggplot2)
library(data.table)
library(stringr)
#=====================================================================================#
beer &lt;- fread(&quot;data/beer_reviews.csv&quot;)
#=====================================================================================#</code></pre>
<p>The dataset has about 1.5 million observations across 14 different observations, so don’t try to open it in LibreOffice.
The reviews come from a variety of different users that have rated the beers based on five different attributes (Appearance, Palate, Aroma, Taste, Overall) and then each beer has a few other variables listed such as its ABV, the brewery it comes from, the beer’s name (duh), and what kind of beer it is.</p>
<pre class="r"><code>names(beer)</code></pre>
<pre><code>##  [1] &quot;brewery_id&quot;         &quot;brewery_name&quot;       &quot;review_time&quot;       
##  [4] &quot;review_overall&quot;     &quot;review_aroma&quot;       &quot;review_appearance&quot; 
##  [7] &quot;review_profilename&quot; &quot;beer_style&quot;         &quot;review_palate&quot;     
## [10] &quot;review_taste&quot;       &quot;beer_name&quot;          &quot;beer_abv&quot;          
## [13] &quot;beer_beerid&quot;</code></pre>
<pre class="r"><code>beer[, .(Number = unique(beer$brewery_name))]</code></pre>
<pre><code>##                             Number
##    1:              Vecchio Birraio
##    2:      Caldera Brewing Company
##    3:       Amstel Brouwerij B. V.
##    4:        Broad Ripple Brew Pub
##    5:   Moon River Brewing Company
##   ---                             
## 5739:        Gattopardo Cervejaria
## 5740:         Brauerei Lasser GmbH
## 5741:        Wissey Valley Brewery
## 5742:      Outback Brewery Pty Ltd
## 5743: Georg Meinel Bierbrauerei KG</code></pre>
<pre class="r"><code>beer[, .(Number = unique(beer$review_profilename))]</code></pre>
<pre><code>##                Number
##     1:        stcules
##     2: johnmichaelsen
##     3:        oline73
##     4:      Reidrover
##     5:   alpinebryant
##    ---               
## 33384:     jennaizzel
## 33385:    mine2design
## 33386:       hogshead
## 33387:     NyackNicky
## 33388:        joeebbs</code></pre>
<pre class="r"><code>beer[, .(Number = unique(beer$beer_name))]</code></pre>
<pre><code>##                        Number
##     1:           Sausa Weizen
##     2:               Red Moon
##     3: Black Horse Black Beer
##     4:             Sausa Pils
##     5:          Cauldron DIPA
##    ---                       
## 56853:      Bear Mountain Ale
## 56854:        Highland Porter
## 56855:       Baron Von Weizen
## 56856:          Resolution #2
## 56857:     The Horseman&#39;s Ale</code></pre>
<pre class="r"><code>beer[, .(Number = unique(beer$beer_style))]</code></pre>
<pre><code>##                               Number
##   1:                      Hefeweizen
##   2:              English Strong Ale
##   3:          Foreign / Export Stout
##   4:                 German Pilsener
##   5:  American Double / Imperial IPA
##  ---                                
## 100:                          Gueuze
## 101:                            Gose
## 102:                        Happoshu
## 103:                           Sahti
## 104: Bière de Champagne / Bière Brut</code></pre>
<p>From a bird’s eye view we have 56,857 unique beers in 104 different categories from 5,743 different breweries and 33,388 unique beer aficionados who have gone out of their way to tell this website what they think about the beers they drink.</p>
<p>Before diving in further, it’s worth doing a preliminary check of the quality of the data (aka we should know if this is BAD (Best Available Data) or has undergone a fair deal of cleaning).
As someone who comes from more of a psychology background, I’ve noticed what certain people consider “clean” when it comes to data varies a lot.</p>
<p>The first thing I check for is if there is any kind of data missing and if there is, is it due to chance?
Or is it due to some sort of systematic variation?</p>
<pre class="r"><code>table(complete.cases(beer))</code></pre>
<pre><code>## 
##   FALSE    TRUE 
##   67785 1518829</code></pre>
<pre class="r"><code>67785/1518829</code></pre>
<pre><code>## [1] 0.04462978</code></pre>
<p>So about 4% of our rows don’t have every entry, so probably not too much cause for concern unless we start getting into specific questions about specific beers.
Looking into this a bit further it seems like it’s just beers missing the ABV of the beer.
Anyone who has made some beer ratings has made ratings on all five variables.
And although it’s only 4% of our entire ratings that don’t have their ABV, comparing that to every beer we have, we see we are actually missing ~25% of the ABV ratings of all of our beers.
That could be a problem later, but it’s good to know about it sooner rather than later.</p>
<pre class="r"><code>beer.complete &lt;- beer[complete.cases(beer)]

beer[!complete.cases(beer)][, .(.N = unique(beer_name))]</code></pre>
<pre><code>##                             .N
##     1: Cauldron Espresso Stout
##     2:    The Highland Stagger
##     3:              Alpha Beta
##     4:          Imperial Stout
##     5:               Megalodon
##    ---                        
## 14106:       English Nut Brown
## 14107:              Hop Common
## 14108:     Very Hoppy Pale Ale
## 14109:       Prohibition Lager
## 14110:           Resolution #2</code></pre>
<pre class="r"><code>14110/56857</code></pre>
<pre><code>## [1] 0.2481665</code></pre>
<pre class="r"><code>beer[969]</code></pre>
<pre><code>##    brewery_id             brewery_name review_time review_overall review_aroma
## 1:      12770 City Grille and Brewhaus  1145738954              4            3
##    review_appearance review_profilename              beer_style review_palate
## 1:                 4         UncleJimbo American Pale Ale (APA)           3.5
##    review_taste     beer_name beer_abv beer_beerid
## 1:            4 City Pale Ale       NA       30088</code></pre>
<p>More problems might come up here or there, but let’s move on the first question.</p>
</div>
<div id="which-brewery-produces-the-strongest-beers-by-abv" class="section level2">
<h2>Which brewery produces the strongest beers by ABV%?</h2>
<p>Answering the first question on the list is pretty straight forward.
Essentially all you need to do is grab all of the observations that have an ABV associated with their rating, and then
get the average ABV of all the beers that that brewery produces.</p>
<pre class="r"><code># Use object before that has only ratings with ABVs 
beer.complete[, .(AvgABV = mean(beer_abv)), by = brewery_name]</code></pre>
<pre><code>##                       brewery_name   AvgABV
##    1:              Vecchio Birraio 5.675000
##    2:      Caldera Brewing Company 6.168849
##    3:       Amstel Brouwerij B. V. 3.816373
##    4:        Broad Ripple Brew Pub 6.006202
##    5:   Moon River Brewing Company 5.724103
##   ---                                      
## 5152:        Gattopardo Cervejaria 6.033333
## 5153:         Brauerei Lasser GmbH 5.200000
## 5154:        Wissey Valley Brewery 5.133333
## 5155:      Outback Brewery Pty Ltd 4.787879
## 5156: Georg Meinel Bierbrauerei KG 5.850000</code></pre>
<pre class="r"><code># Create table that has means and standard deviations of beers by brewery 
# Order them from most to least
abv.counter &lt;- beer.complete[, .(AvgABV = mean(beer_abv), 
                                 SdABV = sd(beer_abv)) , 
                             by = brewery_name][order(-AvgABV)]
abv.counter</code></pre>
<pre><code>##                              brewery_name     AvgABV      SdABV
##    1:                        Schorschbräu 19.2288235 12.3273042
##    2:                       Shoes Brewery 15.2000000  0.0000000
##    3:                Rome Brewing Company 13.8400000  1.9718012
##    4:                   Hurlimann Brewery 13.7500000  0.5752237
##    5:            Alt-Oberurseler Brauhaus 13.2000000         NA
##   ---                                                          
## 5152:             Cerveceria Vegana, S.A.  2.2608696  2.2455490
## 5153: Moskovskaya Pivovarennaya Kompaniya  2.1500000  1.6881943
## 5154:                      Fentimans Ltd.  1.3750000  1.6201852
## 5155:                        Borodino ZAO  0.9666667  0.4041452
## 5156:                    All Stars Bakery  0.5000000  0.0000000</code></pre>
<p>Having this table could be good enough for government work, but looking at the output there are clearly problems, and one thing to consider in this table (and pretty much this whole dataset) is “Is this data point a good representation of what I am trying to measure?”.
Note for example the huge variability as measured by the standard deviation in our top answer as well as the fact that some of the SDs have NAs and there is a value of 0.
Given that, I think it’d be good to put on some sort of threshold that would up the quality of our answers.
One way to do this would be to see exactly how many beers each brewery makes and use that as a proxy for how big the brewery is.</p>
<p>The code below does just that and reveals the variability in terms of size of breweries within this dataset.</p>
<pre class="r"><code># Create table that counts number of beers 
NoOfBeers &lt;- beer.complete[, .(NameOfBeer = unique(beer_name)), 
                           by = brewery_name][, .(.N), by = brewery_name]
NoOfBeers</code></pre>
<pre><code>##                       brewery_name  N
##    1:              Vecchio Birraio  4
##    2:      Caldera Brewing Company 25
##    3:       Amstel Brouwerij B. V.  9
##    4:        Broad Ripple Brew Pub 40
##    5:   Moon River Brewing Company 34
##   ---                                
## 5152:        Gattopardo Cervejaria  3
## 5153:         Brauerei Lasser GmbH  1
## 5154:        Wissey Valley Brewery  3
## 5155:      Outback Brewery Pty Ltd  6
## 5156: Georg Meinel Bierbrauerei KG  2</code></pre>
<pre class="r"><code># Make table that lists each beer with it&#39;s ABV and the name of the brewery
abv.table &lt;- NoOfBeers[abv.counter, on = &quot;brewery_name&quot;]
abv.table</code></pre>
<pre><code>##                              brewery_name  N     AvgABV      SdABV
##    1:                        Schorschbräu 10 19.2288235 12.3273042
##    2:                       Shoes Brewery  1 15.2000000  0.0000000
##    3:                Rome Brewing Company  2 13.8400000  1.9718012
##    4:                   Hurlimann Brewery  3 13.7500000  0.5752237
##    5:            Alt-Oberurseler Brauhaus  1 13.2000000         NA
##   ---                                                             
## 5152:             Cerveceria Vegana, S.A.  2  2.2608696  2.2455490
## 5153: Moskovskaya Pivovarennaya Kompaniya  2  2.1500000  1.6881943
## 5154:                      Fentimans Ltd.  3  1.3750000  1.6201852
## 5155:                        Borodino ZAO  2  0.9666667  0.4041452
## 5156:                    All Stars Bakery  1  0.5000000  0.0000000</code></pre>
<pre class="r"><code># Create z scores 
abv.table[, zAvgABV := scale(AvgABV)]</code></pre>
<p>After visually inspecting the graph on the size of breweries (below), I figured I could just look at breweries that make over five beers (which hopefully wipes out your hipster friend’s “micro brewery” in his basement where he is just trying to make the most potent IPA ever) and then only look at beers that score 4 standard deviations above the mean of all beers in terms of ABV content to narrow down possible candidates.</p>
<pre class="r"><code># How many beers to count for a big brewery? 
hist(NoOfBeers$N, breaks= 200, 
     main = &quot;Distribution of Size of Breweries&quot;, 
     xlab = &quot;Number of Beers Produced by a Brewery&quot;)</code></pre>
<p><img src="/post/2018-01-14-hire-me-as-a-data-scientist-part-i_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>NoOfBeers[N &gt; 200] # Clearly some big breweries here! </code></pre>
<pre><code>##                        brewery_name   N
## 1:    Minneapolis Town Hall Brewery 243
## 2:            Goose Island Beer Co. 304
## 3:   Iron Hill Brewery &amp; Restaurant 269
## 4: Rock Bottom Restaurant &amp; Brewery 522</code></pre>
<pre class="r"><code>abv.table[N &gt;= 5, ][order(-AvgABV)]</code></pre>
<pre><code>##                                              brewery_name   N    AvgABV
##    1:                                        Schorschbräu  10 19.228824
##    2: Brasserie Grain d&#39; Orge (Brasserie Jeanne d&#39;Arc SA)  10 12.445860
##    3:                          Brauerei Schloss Eggenberg  14 11.779681
##    4:                     Brasserie Dubuisson Frères sprl  14 11.432746
##    5:                            Kuhnhenn Brewing Company 142 11.345839
##   ---                                                                  
## 2539:                             Berliner Kindl Brauerei  12  3.532627
## 2540:  Yanjing Pijiu (Guilin Liquan) Gufen Youxian Gongsi   5  3.440000
## 2541:                                            Ochakovo  16  3.203150
## 2542:                        Grogg&#39;s Pinnacle Brewing Co.   6  3.200000
## 2543:                                        Deka Brewery   7  2.620000
##            SdABV   zAvgABV
##    1: 12.3273042 10.235332
##    2:  1.7054879  5.048898
##    3:  3.0759353  4.539520
##    4:  1.6583471  4.274244
##    5:  3.5788003  4.207793
##   ---                     
## 2539:  1.0372607 -1.766396
## 2540:  0.6426508 -1.837221
## 2541:  1.2735986 -2.018323
## 2542:  0.0000000 -2.020731
## 2543:  1.6356553 -2.464215</code></pre>
<pre class="r"><code>hist(abv.table[N &gt;= 5, ][order(-AvgABV)]$zAvgABV,
     xlab = &quot;z Score of ABV&quot;, 
     main = &quot;Distribution of ABV in Breweries that make more than 5 Beers&quot;)</code></pre>
<p><img src="/post/2018-01-14-hire-me-as-a-data-scientist-part-i_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<pre class="r"><code>abv.table[N &gt;= 5 &amp; zAvgABV &gt; 4, ][order(-AvgABV)]</code></pre>
<pre><code>##                                           brewery_name   N   AvgABV     SdABV
## 1:                                        Schorschbräu  10 19.22882 12.327304
## 2: Brasserie Grain d&#39; Orge (Brasserie Jeanne d&#39;Arc SA)  10 12.44586  1.705488
## 3:                          Brauerei Schloss Eggenberg  14 11.77968  3.075935
## 4:                     Brasserie Dubuisson Frères sprl  14 11.43275  1.658347
## 5:                            Kuhnhenn Brewing Company 142 11.34584  3.578800
##      zAvgABV
## 1: 10.235332
## 2:  5.048898
## 3:  4.539520
## 4:  4.274244
## 5:  4.207793</code></pre>
<p>Doing it this way puts Schorschbräu as the highest ABV brewery, which makes sense because <a href="https://www.beeradvocate.com/beer/profile/6513/51466/?ba=wordemupg">they claim to make the world’s strongest beer</a>.
Making a quick plot of the data for our winner and the second place finisher, we see how strong Schorschbräu really is.</p>
<pre class="r"><code>schor.abv &lt;- beer.complete[brewery_name == &quot;Schorschbräu&quot;, 
                           .(beer_name = unique(beer_name)), by = beer_abv]

ggplot(schor.abv, aes(x = beer_name, y = beer_abv)) + 
  geom_bar(stat = &quot;identity&quot;)  + 
  labs( title = &quot;Schorschbräu Beer ABV&quot;, x = &quot;Beer Name&quot;, y = &quot;ABV&quot;) +
   theme(axis.text.x=element_text(angle = -90, hjust = 0)) </code></pre>
<p><img src="/post/2018-01-14-hire-me-as-a-data-scientist-part-i_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>brassOrg.abv &lt;- beer.complete[brewery_name == &quot;Brasserie Grain d&#39; Orge (Brasserie Jeanne d&#39;Arc SA)&quot;, 
                              .(beer_name = unique(beer_name)), by = beer_abv]

ggplot(brassOrg.abv, aes(x = beer_name, y = beer_abv)) + 
  geom_bar(stat = &quot;identity&quot;)  + 
  labs( title = &quot;Brasserie Grain d&#39; Orge Beer ABV&quot;, 
        x = &quot;Beer Name&quot;, 
        y = &quot;ABV&quot;) +
   theme(axis.text.x=element_text(angle = -90, hjust = 0)) + ylim(0, 60) </code></pre>
<p><img src="/post/2018-01-14-hire-me-as-a-data-scientist-part-i_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<p>I think that saying Schorschbräu is technically correct here, but after sharing my findings with my one beer drinking friend
he pointed out that one thing that this analysis did not take into account was that beers
that are traditionally brewed to have a higher ABV (like IPAs and Belgiums) might skew my results.
So if you are a big IPA brewery, you are going to have higher average ABV because of the beers you decide to brew!</p>
<p>So in the true spirit of that <a href="http://drewconway.com/zia/2013/3/26/the-data-science-venn-diagram">data science Venn diagram</a> noting that data scientists need to be flexible in
incorporating others’ domain knowledge, I did another analysis to just show how much an answer can change depending on how you change your operationalization of the question!</p>
<p>Let’s do another one!</p>
<p>First up for this one is making a plot of the data to see how much beers actually vary from type to type.</p>
<pre class="r"><code># Get mean and SD of each beer type 
abv.by.type &lt;- beer.complete[ , .(MeanAbvType = mean(beer_abv), 
                                  SdAbvType = sd(beer_abv)), 
                              by = beer_style]

# For Graphing, order, set style as factor 
ordered.abv.by.type &lt;- abv.by.type[order(-MeanAbvType)]
ordered.abv.by.type$beer_style &lt;- factor(ordered.abv.by.type$beer_style, levels = ordered.abv.by.type$beer_style)

# Code for plot, blogdown crunches the images 
# Average ABV by beer type
# ggplot(ordered.abv.by.type, aes(x = beer_style, y = MeanAbvType)) + 
#  geom_bar(stat=&quot;identity&quot;) +   coord_flip() +
#  labs(title = &quot;Average ABV by Type of Beer&quot;,
#       x = &quot;Beer Style&quot;,
#       y = &quot;Mean ABV, bars represent SD&quot;) +
#  geom_errorbar(aes(ymin=MeanAbvType-SdAbvType, ymax=MeanAbvType+SdAbvType)) +
#  theme_bw()</code></pre>
<p><img src="/img/abvtemp.png" /></p>
<p>So you can see here that if you wanted to have a higher ABV on average for your brewery, you’d benefit from having more IPAs, Barley Wines, and Belgian Stouts.</p>
<p>Now with average ABV for each beer, let’s then match that to our big list, find how each beer fairs against its own category, sort them, and then combine them with our information from before on how big the brewery is.
For the purposes of this example, let’s only look at breweries that have over 100 beers in the database and look the top 20.</p>
<pre class="r"><code># Combine ABV per type data with complete data
beer.complete.avg.abv &lt;- abv.by.type[beer.complete, on = &quot;beer_style&quot;]
# Make new z score variable based on other beers in group
beer.complete.avg.abv[, zABV := (beer_abv-MeanAbvType)/SdAbvType]  
# Get averages per brewery on z variable
zAvgBeers &lt;- beer.complete.avg.abv[, .(AvgAbvZ = mean(zABV)), by = brewery_name][order(-AvgAbvZ)]
# Combine back with our data on proxy of size of brewery
BreweryAndAvgAbv &lt;- zAvgBeers[NoOfBeers, on = &quot;brewery_name&quot;]
# And the winner is...
BreweryAndAvgAbv[N &gt; 100][order(-AvgAbvZ)][1:25]</code></pre>
<pre><code>##                               brewery_name     AvgAbvZ   N
##  1:               Kuhnhenn Brewing Company  1.26003627 142
##  2:                     Cigar City Brewing  0.87721989 171
##  3:                             The Bruery  0.74965237 143
##  4:     Three Floyds Brewing Co. &amp; Brewpub  0.71875251 128
##  5: Flossmoor Station Restaurant &amp; Brewery  0.53182569 114
##  6:                     Brouwerij De Molen  0.51695738 119
##  7:               Jackie O&#39;s Pub &amp; Brewery  0.40179915 105
##  8:                          Mikkeller ApS  0.37012567 184
##  9:               Founders Brewing Company  0.24770929 130
## 10:                      Deschutes Brewery  0.19390121 127
## 11:      Port Brewing Company / Pizza Port  0.19357914 194
## 12:                     Fitger&#39;s Brewhouse  0.18931699 111
## 13:                       Bullfrog Brewery  0.10590796 121
## 14:                Victory Brewing Company  0.09970522 107
## 15:         Iron Hill Brewery &amp; Restaurant  0.03563186 269
## 16:                  Goose Island Beer Co.  0.01475446 304
## 17:                Sly Fox Brewing Company -0.01733499 140
## 18:              Sierra Nevada Brewing Co. -0.07417651 121
## 19:                      Stone Brewing Co. -0.08646265 119
## 20:              Cambridge Brewing Company -0.12326285 124
## 21:       Rock Bottom Restaurant &amp; Brewery -0.26029542 522
## 22:                Willimantic Brewing Co. -0.28003004 134
## 23:     John Harvard&#39;s Brewery &amp; Ale House -0.29598861 151
## 24:          Minneapolis Town Hall Brewery -0.41963873 243
## 25:                                   &lt;NA&gt;          NA  NA
##                               brewery_name     AvgAbvZ   N</code></pre>
<p>Looking at this list, we get a totally different answer.
It appears that on average <a href="https://www.beeradvocate.com/beer/profile/2097/">Kuhnhenn Brewing Company</a> brews their beers 1.26 standard deviations above the mean of all other beers in that category!</p>
<p>Both answers could be technically correct, but more importantly demonstrate how important it is to come up with how you frame your question first, and then try to answer it so you don’t end up going on a fishing expedition!</p>
<p>Moving on to question #2!</p>
</div>

        </p>
    </div>
    

    

    <div class="page-footer">
        
        <hr class="footer-divider">
        
            <a class="tag" href="/tags/r">#R</a>
        
            <a class="tag" href="/tags/5-minute-reads">#5 Minute Reads</a>
        
      
    </div>


        

<link rel="stylesheet" type="text/css" href="/css/katex.min.css" crossorigin="anonymous">
<script type="text/javascript" src="/js/katex.min.js" crossorigin="anonymous"></script>
<script type="text/javascript" src="/js/auto-render.min.js"onload="renderMathInElement(document.body);" crossorigin="anonymous"></script>

        </div>
        <footer class="footer-mobile">
	<div class="social-icons">
        
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Email">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M25.2794292,5.59128519 L14,16.8707144 L2.72057081,5.59128519 C3.06733103,5.30237414 3.51336915,5.12857603 4,5.12857603 L24,5.12857603 C24.4866308,5.12857603 24.932669,5.30237414 25.2794292,5.59128519 Z M25.9956978,6.99633695 C25.998551,7.04004843 26,7.08414302 26,7.12857603 L26,20.871424 C26,21.0798433 25.9681197,21.2808166 25.9089697,21.4697335 L18.7156355,14.2763993 L25.9956978,6.99633695 Z M24.9498374,22.6319215 C24.6672737,22.7846939 24.3437653,22.871424 24,22.871424 L4,22.871424 C3.5268522,22.871424 3.09207889,22.7071233 2.74962118,22.432463 L10.0950247,15.0870594 L13.9848068,18.9768415 L14.1878486,18.7737996 L14.2030419,18.7889929 L17.6549753,15.3370594 L24.9498374,22.6319215 Z M2.00810114,21.0526627 C2.00273908,20.9929669 2,20.9325153 2,20.871424 L2,7.12857603 C2,7.08414302 2.00144896,7.04004843 2.00430222,6.99633695 L9.03436454,14.0263993 L2.00810114,21.0526627 Z"></path>
        </svg>
    </a>
    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Twitter">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M8.991284,24.971612 C19.180436,24.971612 24.752372,16.530224 24.752372,9.210524 C24.752372,8.970656 24.747512,8.731868 24.736496,8.494376 C25.818008,7.712564 26.758256,6.737 27.5,5.62622 C26.507372,6.067076 25.439252,6.364292 24.318752,6.498212 C25.462472,5.812628 26.340512,4.727444 26.754584,3.434036 C25.684088,4.068536 24.499004,4.53002 23.23724,4.778528 C22.226468,3.701876 20.786828,3.028388 19.193828,3.028388 C16.134404,3.028388 13.653536,5.509256 13.653536,8.567492 C13.653536,9.0023 13.702244,9.424904 13.797176,9.830552 C9.19346,9.599108 5.11106,7.39472 2.3792,4.04294 C1.903028,4.861364 1.629032,5.812628 1.629032,6.827072 C1.629032,8.74904 2.606972,10.445612 4.094024,11.438132 C3.185528,11.41016 2.331788,11.160464 1.585184,10.745096 C1.583888,10.768208 1.583888,10.791428 1.583888,10.815728 C1.583888,13.49888 3.493652,15.738584 6.028088,16.246508 C5.562932,16.373084 5.07326,16.44134 4.56782,16.44134 C4.210988,16.44134 3.863876,16.406024 3.526484,16.34144 C4.231724,18.542264 6.276596,20.143796 8.701412,20.18894 C6.805148,21.674696 4.416836,22.56008 1.821488,22.56008 C1.374476,22.56008 0.93362,22.534592 0.5,22.4834 C2.951708,24.054476 5.862524,24.971612 8.991284,24.971612"></path>
        </svg>
    </a>
    

    

    

    

    

    

    

    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="LinkedIn">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M2,3.654102 C2,2.69908141 2.79442509,1.92397846 3.77383592,1.92397846 L24.2261641,1.92397846 C25.2058917,1.92397846 26,2.69908141 26,3.654102 L26,24.3462148 C26,25.3015521 25.2058917,26.0760215 24.2261641,26.0760215 L3.77383592,26.0760215 C2.79442509,26.0760215 2,25.3015521 2,24.3465315 L2,3.65378524 L2,3.654102 Z M9.27526132,22.1415901 L9.27526132,11.2356668 L5.65030092,11.2356668 L5.65030092,22.1415901 L9.27557808,22.1415901 L9.27526132,22.1415901 Z M7.46341463,9.74691162 C8.72727273,9.74691162 9.51409566,8.90940767 9.51409566,7.86284447 C9.49033893,6.79252455 8.72727273,5.97846056 7.48748812,5.97846056 C6.24675325,5.97846056 5.43649034,6.79252455 5.43649034,7.86284447 C5.43649034,8.90940767 6.22299652,9.74691162 7.4396579,9.74691162 L7.46309788,9.74691162 L7.46341463,9.74691162 Z M11.2815965,22.1415901 L14.9062401,22.1415901 L14.9062401,16.0519481 C14.9062401,15.7263225 14.9299968,15.4000634 15.0256573,15.1675641 C15.2876148,14.5159962 15.8840672,13.8416218 16.8856509,13.8416218 C18.1970225,13.8416218 18.7218879,14.8416218 18.7218879,16.3078872 L18.7218879,22.1415901 L22.3465315,22.1415901 L22.3465315,15.8885017 C22.3465315,12.5388027 20.5584416,10.9800443 18.1735825,10.9800443 C16.2182452,10.9800443 15.3595185,12.072854 14.8824834,12.8172315 L14.9065569,12.8172315 L14.9065569,11.2359835 L11.2819132,11.2359835 C11.3291099,12.2591067 11.2815965,22.1419069 11.2815965,22.1419069 L11.2815965,22.1415901 Z"></path>
        </svg>
    </a>
    

    

    

    

    

    

    

    
    
    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="GitHub">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M13.9988029,1.32087331 C6.82105037,1.32087331 1,7.14112562 1,14.3212723 C1,20.0649109 4.72454649,24.9370678 9.89038951,26.6560892 C10.5408085,26.7757983 10.7778323,26.374374 10.7778323,26.0296121 C10.7778323,25.7215609 10.7666595,24.9035493 10.760275,23.8189856 C7.14426471,24.6042767 6.38131925,22.0760223 6.38131925,22.0760223 C5.78995672,20.5740732 4.93762853,20.1742451 4.93762853,20.1742451 C3.75729765,19.3682044 5.02701126,19.3841656 5.02701126,19.3841656 C6.33183953,19.4759425 7.01817121,20.7241085 7.01817121,20.7241085 C8.17775254,22.7104801 10.0611744,22.1366749 10.8017741,21.8038838 C10.919887,20.9643246 11.2558703,20.3913175 11.6269683,20.066507 C8.74038491,19.7385043 5.70536235,18.6228163 5.70536235,13.6413251 C5.70536235,12.2223743 6.21213051,11.0611968 7.04370914,10.1530044 C6.90963504,9.82420367 6.46351945,8.50181809 7.17139875,6.71256734 C7.17139875,6.71256734 8.26234691,6.36301702 10.7459099,8.04532771 C11.78259,7.75642995 12.8950858,7.61277914 14.000399,7.60719272 C15.1049142,7.61277914 16.2166119,7.75642995 17.2548881,8.04532771 C19.736855,6.36301702 20.8262071,6.71256734 20.8262071,6.71256734 C21.5356825,8.50181809 21.0895669,9.82420367 20.9562909,10.1530044 C21.7894656,11.0611968 22.2922435,12.2223743 22.2922435,13.6413251 C22.2922435,18.6355852 19.2524325,19.734514 16.3570705,20.0561322 C16.8231376,20.4575564 17.2389269,21.2508282 17.2389269,22.4638795 C17.2389269,24.2012564 17.2229657,25.603448 17.2229657,26.0296121 C17.2229657,26.3775663 17.4575954,26.7821827 18.116793,26.6552912 C23.2786458,24.9322794 27,20.0633148 27,14.3212723 C27,7.14112562 21.1789496,1.32087331 13.9988029,1.32087331"></path>
        </svg>
    </a>
    

    
    
    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Google Scholar">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
             <path d="M15.7399177,5.48151786 C15.149924,4.82272859 14.4663239,4.49480724 13.6933878,4.49480724 C12.8185607,4.49480724 12.1471312,4.80966127 11.6791845,5.43796013 C11.2112379,6.06433732 10.9771365,6.82326666 10.9771365,7.71483354 C10.9771365,8.47423262 11.1052474,9.24733956 11.3616402,10.035649 C11.6170934,10.8236168 12.0350768,11.5270314 12.6210136,12.1470458 C13.2049434,12.7685974 13.8844439,13.0787968 14.6564833,13.0787968 C15.5171327,13.0787968 16.189459,12.7903763 16.671626,12.2137916 C17.1517432,11.6379755 17.3927199,10.9111166 17.3927199,10.035649 C17.3927199,9.29000051 17.2655484,8.50924961 17.0102233,7.69296927 C16.7561365,6.87562134 16.3319184,6.13812924 15.739875,5.48156056 L15.7399177,5.48151786 Z M24.3072528,4.96950105 L24.3072528,13.3462071 C24.3072528,13.7339989 23.9898792,14.0515006 23.6019592,14.0515006 L23.3422783,14.0515006 C22.9543156,14.0515006 22.6369848,13.7341271 22.6369848,13.3462071 L22.6369848,4.96950105 C22.6369848,4.62513879 22.5869788,4.33765779 23.068249,4.27714671 L23.068249,3.16262405 L19.3634081,6.20120253 C19.4061972,6.28058863 19.446851,6.33132057 19.4854124,6.39789556 C19.8110278,6.97418137 19.9768461,7.69087679 19.9768461,8.56681414 C19.9768461,9.23824368 19.8649625,9.84134739 19.638078,10.3740328 C19.4122611,10.9065473 19.1375912,11.3415267 18.817143,11.6765369 C18.496652,12.0127855 18.1752643,12.3201237 17.8538766,12.5967152 C17.5324462,12.8739047 17.2577763,13.162923 17.0328135,13.4629589 C16.8060571,13.7620125 16.6932767,14.0712297 16.6932767,14.3917206 C16.6932767,14.7126813 16.8397076,15.0387237 17.1317151,15.3673283 C17.4226551,15.6968724 17.7805972,16.0162103 18.2038758,16.3317049 C18.6279231,16.6450216 19.0510736,16.9928002 19.4743522,17.3712399 C19.8985703,17.74921 20.2545052,18.2354765 20.5454452,18.8259399 C20.8385631,19.4186239 20.9848231,20.071093 20.9848231,20.7882582 C20.9848231,21.7343577 20.7435475,22.5887297 20.2626616,23.3491963 C19.7802812,24.1064175 19.1518542,24.7106315 18.3796867,25.1537246 C17.6054695,25.599807 16.777531,25.9355858 15.8945476,26.1623422 C15.0097279,26.3870488 14.1317408,26.5 13.2548639,26.5 C12.7014246,26.5 12.1429889,26.4573818 11.5814359,26.3697112 C11.0178757,26.2822114 10.4532907,26.1276668 9.8847343,25.9098782 C9.31502485,25.6906377 8.81052389,25.4214338 8.37319577,25.0981672 C7.93475736,24.778146 7.58181166,24.3652016 7.3111559,23.862238 C7.04054285,23.3591036 6.90615445,22.7936645 6.90615445,22.1655364 C6.90615445,21.4203577 7.1136515,20.7291563 7.52975591,20.0847582 C7.94586031,19.4451002 8.49707907,18.9108775 9.18272893,18.487727 C10.3789864,17.7434877 12.2558547,17.2836547 14.8102164,17.1098936 C14.2262867,16.3799173 13.9333396,15.6928582 13.9333396,15.0498693 C13.9333396,14.6841125 14.0289531,14.2920503 14.218173,13.8687717 C13.9130554,13.9113899 13.5987992,13.9355175 13.2781801,13.9355175 C11.9059836,13.9355175 10.7472627,13.4894351 9.80628769,12.5911638 C8.86535538,11.6944724 8.39535897,10.5719642 8.39535897,9.21488479 C8.39535897,9.07298054 8.39941581,8.94802965 8.40970739,8.8095417 L2.83316537,8.8095417 L11.2417283,1.5 L25.1668346,1.5 L23.87996,2.50451805 L23.87996,4.27748834 C24.3577712,4.3388962 24.3072955,4.62607827 24.3072955,4.96950105 L24.3072528,4.96950105 Z M15.8172967,17.9839947 C15.6566455,17.9549562 15.430914,17.9386434 15.1399313,17.9386434 C14.512273,17.9386434 13.8947782,17.9941154 13.2885571,18.1048887 C12.6822934,18.2126727 12.084186,18.3947184 11.4941496,18.6515809 C10.9019353,18.906906 10.423996,19.2823566 10.0597766,19.7787865 C9.69355004,20.274576 9.51150436,20.858463 9.51150436,21.5303623 C9.51150436,22.1706609 9.67215551,22.7419077 9.99371402,23.2394479 C10.3142049,23.7338281 10.7373127,24.1208513 11.2632509,24.3980408 C11.7891891,24.6756999 12.3405787,24.8854176 12.916224,25.0231795 C13.4929795,25.1600875 14.0799412,25.2311463 14.6780913,25.2311463 C15.8610679,25.2311463 16.8794647,24.9647609 17.7338794,24.4320756 C18.5863724,23.899561 19.0135798,23.0772595 19.0135798,21.9672634 C19.0135798,21.7338025 18.9810823,21.5040141 18.916856,21.2796064 C18.8498112,21.0527219 18.7835352,20.8585057 18.7185829,20.6972567 C18.6534171,20.5389543 18.529363,20.3483679 18.3462498,20.1286576 C18.1642041,19.9083067 18.0248194,19.7455631 17.9310848,19.6372239 C17.8354714,19.5253403 17.6565431,19.3656714 17.3929761,19.1545445 C17.131587,18.9425209 16.9647012,18.8103104 16.8904822,18.7614574 C16.8172027,18.7100422 16.6270434,18.5711699 16.3207728,18.3458227 C16.0147157,18.1186393 15.8468903,17.9981723 15.8173394,17.983952 L15.8172967,17.9839947 Z"></path>
        </svg>
    </a>
    

    

    
    <a class="social-icon" href="#" target="_blank" rel="noopener" title="Orcid">
        <svg width="28px" height="28px" viewBox="0 0 28 28" version="1.1" fill="#ABABAB" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink">
            <path d="M27,14 C27,21.1804687 21.1804687,27 14,27 C6.81953125,27 1,21.1804687 1,14 C1,6.81953125 6.81953125,1 14,1 C21.1804687,1 27,6.81953125 27,14 Z M9.76484375,19.9109375 L9.76484375,13.9492188 L9.76484375,9.03359375 L8.20078125,9.03359375 L8.20078125,19.9109375 L9.76484375,19.9109375 Z M12.0601563,9.03359375 L12.0601563,19.9210938 L16.3054688,19.9210938 C19.890625,19.9210938 22.0742188,17.2703125 22.0742188,14.4773437 C22.0742188,11.9078125 20.3070313,9.03359375 16.2851563,9.03359375 L12.0601563,9.03359375 Z M13.6242188,18.509375 L13.6242188,10.4453125 L16.03125,10.4453125 C19.078125,10.4453125 20.4695313,12.29375 20.4695313,14.4773437 C20.4695313,15.8179688 19.6570313,18.509375 16.1125,18.509375 L13.6242188,18.509375 Z M10.0085938,6.76875 C10.0085938,6.21015625 9.5515625,5.74296875 8.9828125,5.74296875 C8.4140625,5.74296875 7.95703125,6.2 7.95703125,6.76875 C7.95703125,7.32734375 8.4140625,7.79453125 8.9828125,7.79453125 C9.5515625,7.79453125 10.0085938,7.32734375 10.0085938,6.76875 Z"></path>
        </svg>
    </a>
    

    

</div>




	<div class="footer-mobile-links">
		<p><a href="https://github.com/kimcc/hugo-theme-noteworthy" target="_blank" rel="noopener">Noteworthy theme</a></p>
		<span class="divider-bar">|</span>
		<p><a href="https://gohugo.io" target="_blank" rel="noopener">Built with Hugo</a></p>
	</div>

	<script src="https://example.com/js/main.min.c1aee25a817e9beb1f9c4afd9d62311227a7f5e46720e404dc1dda97281f47f2.js" integrity="sha256-wa7iWoF+m+sfnEr9nWIxEien9eRnIOQE3B3alygfR/I=" crossorigin="anonymous"></script>
</footer>
    </body>
</html>