---
title: Begin the Fugue, Part I
author: ~
date: '2020-06-29'
slug: begin-the-fugue-part-i
categories: [data science, education]
tags: [data science, education]
subtitle: ''
summary: ''
authors: []
lastmod: '2020-06-29T09:48:55+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

The past few months have been pretty exhausting.
On top of all things lockdown and the global pandemic, a little over a month ago I was told that my job was “at risk” of redundancy.
After going through the full collective consultation period, today is my last official day working as an employee of Flatiron School.
While this has been a bit of a shock, I’ve been thinking about my time at Flatiron these past few weeks and as my first prelude comes to its final [PAC](https://en.wikipedia.org/wiki/Cadence#:~:text=In%20a%20perfect%20authentic%20cadence,found%20at%20structurally%20defining%20moments.) and brace for the subsequent fugue^[In keeping with the metaphor I used when I wrote about joining Flatiron], I always find that writing about what is on my mind really helps me see the bigger picture. 

Looking over everything I did mull over, it’s quite long so I’ve broken it up into three parts:

* What Did I Just Do?: A prosaic setting of my resume
* Vocationtional Vicissitudes: My thoughts on why vocationalism versus the liberal arts helps me understand higher education
* My Dream AD (Applicant’s Description): Things I Might Want to do Next with My Job

As always, thanks for caring about me and reading my blog posts. 

## What Did I Just Do?

For the past nine months I have been a Lead Instructor of Data Science at the London campus of the Flatiron School. 
During my time there, I’ve led four different cohorts of students through an intensive fifteen week program where students with not much experience in coding or statistics or machine learning immerse themselves in order to learn as much as they possibly can from their instructors, the written curricula, as well as their peers.

The bootcamp approach to learning is extremely different from that of traditional, liberal arts, higher-ed and while it can get a bad reputation for not being as exhaustive as spending four years doing something (duh), there are many things that bootcamps really excel at such as having so many learners concentrated into one space, all at about the same level of understanding, with near constant access to instructors to help guide a herd of overly eager learners. 

At Flatiron School, I was mainly responsible for delivering material for the first two modules they took which were “Python for Data Science” and “Probability and Statistics” and was supported by a team of four wonderful people.

Many of us are now also on the job market now and if you are reading this and want to pick up the scraps of a fantastic team, go add these people on LinkedIn. All you have to do is click the links below. They’re all fantastic educators and even better data scientists. 

* [Wachira Ndagia](https://www.linkedin.com/in/wachirandaiga/) 
* [Dan Sanz Becerril](https://www.linkedin.com/in/danielsanzbecerril/)
* [Javi Fernandez Suarez](https://www.linkedin.com/in/javier-f-s/) 
* [Ioana P](https://www.linkedin.com/in/ioanapr/)

I also lectured a bit on other topics that I personally like a lot such as clustering, principal components analysis, and was always the one to give my obligatory Introduction to R and the Tidyverse workshop. We taught mostly Python, so I wouldn’t have been able to sleep at night without introducing them to R. 

As of today, we’ve graduated a sizeable batch of students and have placed many of them in jobs.^[I don't want to go into the numbers I keep here since that probably counts as sensative information to post publicly, but the students are doing well. We'll have to wait for our next third part audit for the official numbers.] 
We're not at 100% yet like our [Software Engineering program was able to do](https://hi.flatironschool.com/rs/072-UWY-209/images/Flatiron%20School%20Jobs%20Report.pdf?_ga=2.75036818.1013998130.1593420746-1423311562.1570117877), but I get messages from students when they eventually get jobs and it’s always the best part of my day.
Our students have gone on to work from companies ranging from start-ups, to educational programs like Flatiron School, to more high visibility brands like Nielsen and the Bank of England.

In addition to all things teaching, I also got my first taste of being part of senior management, so I got to be on the hiring side of things for once.
I now understand what people mean when they say [people will only look at your resume less than a minute](https://jobs.telegraph.co.uk/article/does-your-cv-pass-the-30-second-test-/#:~:text=Research%20shows%20that%20most%20employers,CV%20was%20just%206.25%20seconds.).
Being on the other side of the interviewing power-dynamic was surprisingly one of the most valuable experiences I will remember going forward.
I’ve also felt how the volatility of a business’ performance directly affects one’s work since our parent company was WeWork.
There were definitely ups and downs.

Near the end of my time, I also got to help out with a bit of the curriculum development (I got to write some of the R materials for our graduate’s continuing education) that you can check out on the newly minted [Teaching](https://davidjohnbaker.rbind.io/teaching/) section of my website.

It was a lot of work a lot of the time (especially at the start of the role and then again when we had to jump online) and it was 180 degrees in the direction of what I was doing before (writing my dissertation alone in my flat).
And although it wasn’t what I thought I would be doing straight after my PhD, I learned a ton from the work and found many aspects of the job very enjoyable. 

## The Good 

By far, the best part of the job was working with the bootcamp students.
This group of students was by far the most engaged collective of learners I have ever worked with.
To contextualise this, prior to teaching data science at Flatiron, the students from the two areas subjects in higher education I had experience with were both music theory and aural skills (a subset of music notorious for having undergraduates historically question the content area’s utility) as well as statistics for doctoral level psychologists (where a majority of the class was clinical psychologists who, for good reason, question both the quantification, reficication, and reductionism of quantitative methods).

In contrast to undergraduate music majors and clinical psychologists^[Obviously there were some in each group that were really into each class, I don’t mean to portray this as apathy], none of the students at Flatiron were in my classes because they were “required to for graduation” and instead most of them had quit their jobs hoping to change the entire trajectory of their career.
You fork out a lot of cash to do programs like this and that’s not something they took lightly as students and thus it was not something we took lightly as instructors. 

As a result of this large time and financial investment, the students would absolutely rinse myself and the other instructors for questions every day to the point that by 6:00PM I was totally exhausted from so much face-to-face work. 
This constant engaging with instructors and asking as many questions as possible is actually one of the big appeals of this kind of flavor of bootcamp; there are not many other educational settings where students have so much direct access to instructors and peers who are all on the same page.

While we did our best to set boundaries with students it was hard not to engage with people who were so eager to learn.
The real trick that I eventually learned was to try to get the students to essentially bootstrap each other’s learning and move away from the sage-on-the-stage approach and move over towards as much group and active learning as possible.
I learned a lot about giving up control in the classroom and what you get when you start to acknowledge the fact that when you have adult learners, they bring with them far more life experience than those fresh out of school.

As a result of all this rapid learning, the last major thing that I loved about this job was getting to see so many students grow so quickly during their time as a bootcamp student.
Of course it’s true that you’re never going to learn everything in a bootcamp, but these environments are designed to get someone from near zero to competence so they can get in their own self-directed learning feedback loops where they can start critically thinking rather than adopting a pumping them full of knowledge approach. 

Now teaching in a bootcamp setting was not like anything I had taught in before.
The goal wasn't to teach people this history of science or competing philosophies of science throughout the 20th century (though I did weave a lot of that in my lectures, not gonna lie); it was straight up about getting people the tools they need to get a job. 

For this reason, I've now spent a lot of time thinking about the idea of vocationalism versus liberal arts education which I elaborate  on in [Part II](https://davidjohnbaker.rbind.io/post/begin-the-fugue-part-ii/). 
