---
title: 'Life after a PhD in Systematic Musicology: How You Might Prepare for Industry?'
author: ~
date: '2020-06-09'
slug: life-after-a-phd-in-systematic-musicology-how-you-might-prepare-for-industry
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-06-09T09:29:51+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

> This post originally appeared on the SysMus blog on June 9th, 2020. Find the original post [here](https://sites.google.com/view/sysmus/blog#h.p_1a7GZpeLXPSt).

## Introduction

You don’t get to be a grad student forever. 
At some point, you will take everything you’ve been working on in the past however many years, bundle it into a few hundred page document, defend it, and be immensely proud of the fact that you completed a doctoral degree on the topic of systematic musicology. 
In a utopian situation, you take a few weeks off after your defense, then come back to “reality” or the “real world” and consider what you want to do next. 

Maybe upon your return you get lucky and apply for a position at a university and are able to start teaching and researching right away. 
Or maybe you get a postdoc, pack up your bags and move to a new city to continue on your academic adventure for a few years, or maybe you end up taking an adjunct gig somewhere and have to teach part-time with no guarantee of future employment at something near a living wage. 
Or maybe you take a good look five, ten, or twenty years down the road and think to yourself: besides academia, what else is out there? 
What if you wanted to get a job in industry? 
Will I never get to do research again if I “leave academia”?

How does a graduate student in systematic musicology explore what else is out there? 
While there’s an entire culture built around how to continue in academia, there’s not nearly as much available for grad students to figure out how to land an industry job from within the academy. 

What benefits could preparing for being employable in industry have? 
And what steps could you take today in order to achieve these goals this week? In this post, I’d like to directly address these questions in order to provide advice for current graduate students in the SysMus community.

Before I get going, I assume that if you’re reading this post, you’re a graduate student (in systematic musicology specifically) and are interested in the idea of finding work after graduate school in industry. By industry, I mean literally any job that is not an academic job (aka what most of the world does). Specifically, I want to give four pieces of advice and the reasons behind  them as to how you can best prepare yourself for getting a job in industry. It’s the how and why of what I wish someone would have told me a few years ago.

If you don’t want to read the rest of the post and just want the actionable items, here they are:

1. Make a LinkedIn account but don’t position yourself as an academic.
2. Ask people who do the job that you are interested in doing for help. 
3. Create an online presence. 
4. Get better at programming.

Though as academics we’re never satisfied with just the answer to what we should do; we want to know how and why. With that in mind, let’s get started investigating why I think you should do these four things if you're interested in a job in industry. 

But why take my advice? Since this isn’t my personal blog, I should probably introduce myself and establish a bit of credibility before taking some random advice from some dude on the internet. My name is Dave (though you’ll find me on the internet as @DavidJohnBaker since I have a pretty basic Western name) and as of last year, I completed my Ph.D. in Music Theory at Louisiana State University where I investigated how tools from computational musicology and cognitive psychology can help inform how we teach aural skills in music school. 

While a grad student, I went to a couple of SysMuses (is that the plural?) in 2014 (Goldsmiths) and 2017 (Queen Mary) currently am serving as the trainee representative for the Society of Music Perception and Cognition. I went directly from my PhD to working a non-academic job where I am currently Lead Instructor of Data Science at Flatiron School in London, England. In my current position I teach people skills they need in order to get jobs in industry, specifically jobs as (~junior) data scientists. I watch people make this transition into industry literally every day and as a former member of the SysMus community, am more than willing to try to help out any SysMus people I can if they’re interested in what I can offer in the future. 

Ok, let’s get to it.

## Make a LinkedIn

If you have spent any time in academia, you know that no one in academia uses LinkedIn. In fact, I have heard some senior academics brag about the fact that they literally do not get the point of the platform, don't have an account, and pride themselves in not knowing about it at all. These are probably the same people who also boast about not knowing the difference between a CV and a resume. 

This makes sense in a lot of ways.

Academics don't need LinkedIn because the currency of what we value as academics is not an apparent part of the website's infrastructure. Furthermore, what “counts” in academia does not “count” in most industry jobs. There's no great way to display all your ever-increasing publication record, the pedigree of the institutions from which you have worked your way through, or any sort of teaching or service accolades you've accumulated over the years.

And that's OK. Your persona on LinkedIn shouldn't be your academic persona. 

If you're staring at your yet-to-be-fleshed-out LinkedIn page and are having trouble inserting your square block of an academic persona into industy's round hole, this trouble is just a symptom of the real reason I picked the first piece of advice as creating a LinkedIn account: you first need to realise that your value working in industry comes from your ability to add value to an organization; your online profile should reflect you understand that.

So how do you do that?

The first step is trying to figure out what value you can bring to an organization. If you're working for a company (as opposed to a charity/not-for-profit), this value best translates as the literal monetary value that you will be able to bring to the company. You need to think about ways that you can position yourself to make it very clear via how you present yourself that you understand  the role you are about to undertake is to create value for the company. 

Can you do analyses that will make their marketing more efficient? Can you write a small classifier that helps eliminate bots from their platform? Are you great at communicating the value of your work to non-technical stakeholders? 

You should ask yourself: how can I best present myself on LinkedIn in order to communicate that the skills that I have are directly beneficial to the company that I will work for? 

Just like re-writing your #scicomm blog posts and tweets to make it easier for the general public to understand the multi-level mixed model you ran and wrote up in your most recently published peer-reviewed journal article, you need to rephrase what you can do in the language of the industry you want to enter.

A lot of this comes from talking to people currently working in the area you want to break into (covered in my next point). For example, in the world of data science this can range from understanding that your background as a music psychologist in experimental design needs to be rephrased as proficiency in AB testing or maybe causal inference. You can use your latest paper you've published as a vehicle to talk about how you excel at taking ill-defined problems, turning them into something quantifiable, performing some sort of reproducible analysis on this, then sharing the importance and results of you  work with both technical (fellow academics) and non-technical stakeholders. 

I'll lastly note here that when you are advocating for yourself on LinkedIn, I'd say it's better to NOT try to brand yourself as an academic, but rather the job title that you eventually want. In my case, my LinkedIn is me as a data scientist and educator. Am I really that? Who knows. You kind of are who you say who you are, you just need to be ready to back it up. For whatever job you want to do, you just need to be able to somehow to demonstrate you know what the requirements of the job are and that you can do that. 
In terms of industry, the closest job that my skills align with is data scientist and identifying as that (even though I don’t know if that’s how I’d describe how I think of myself) makes it easier for others to get what I do.

I felt uncomfortable as a grad student at first calling myself a data scientist having never had a job where I had that title, but if you are graduate level scientist and understand basic inferential statistics, can spend some time and page your way through some introductory machine learning textbooks (for example, Introduction to Statistical Learning) , and can run a linear regression in R or Python and correctly interpret it, you're more than qualified to at least put your title as a Junior Data Scientist who is looking for roles. If not, see point three below. 

As for other jobs that you might want, a large part of this is going to be doing research (what we do best) in the area you want to enter then positioning yourself accordingly. 

Remember, you can always learn new models or frameworks, one of your biggest assets as a grad student in systematic musicology is the ability to learn and synthesize complex things quickly.

Don't worry that your academic side doesn't show on LinkedIn, just add a note that if the person visiting your page on LinkedIn wants to see your academic side, check out your website or Google Scholar. Even though as a grad student your identity is probably 100% intertwined with your academic work, for your own mental health, it’s probably time to start to separate your identity from your work. And what better way than to have a LinkedIn persona that showcases how what you know can be applied elsewhere. 

Of course this will take a bit of research to find out how best to communicate this all, but research is what we academics do best! 

## Ask for Help 

Just like academia, the world of industry is also hugely about who you know and how they can help you. Unlike academia, things in the world of industry move at a much faster rate and there's a lot more off an ebb and flow in when and where you can get hired to do what. 

So how do you navigate this new space?

You need to ask for help via some sort of network. Granted, when you are first looking into entering the world of industry, you probably don't know too many people, but if you reach out to those you do know (especially those who can relate to your current situation, former academics) I’d bet you'll be very surprised of how supportive people can be. 

Specifically, how do you do this?

Often it's a matter of adding someone on LinkedIn (LinkedIn is not like Facebook, people add pretty much anyone looking to connect, especially if it comes with a meaningful note), tweeting to someone you think might be helpful, or asking around in your current academic network about people who you can best reach out to in order to start  building those bridges. If they can help, most likely they will; If they can't help, they probably will direct you to someone who is better suited for your specific situation. If this doesn’t happen, you can message me and I’d be more than happy to try to help you out. 

If there's some sort of professional space that you are looking to enter that doesn't have an obvious person-you-know point of entry, one of the other highly suggested "things to do" is to go to some sort of Meet Up around the topic you're interested in. People who go to meetups in general all tend to be interested in the same thing (obviously, or they wouldn't spend their free time going to them) and are often looking to grow their community so attending an event is a great way to show your interest. Right now (2020), many physical events are currently cancelled, but this doesn’t mean there are not stil online events. People are adapting quickly. 

So what do you even message them about?

Well you don't really have to know exactly what you want, but remember it's always easier to give people specific requests when you approach them and say something like:

"I want to be able to apply for jobs in music and advertising in 8 months time, what  should I do to best prepare for that and work at a company like Shazam?" 

Though don’t feel like you need to know exactly what you want.  You should also feel free to  message people and ask for guidance in the form of an informational interview. There's a lot of information on the web on this, so I won't go too much into that here.^[https://hbr.org/2016/02/how-to-get-the-most-out-of-an-informational-interview]

## Have an Online Presence 

In addition to just having a LinkedIn account (your industry Google Scholar!), I think it also helps to have a bit of an online presence. This could mean having a Twitter feed, ideally a website and possibly even a blog. If you're interested in reasons as why you might want to do this, [check out this post here](http://varianceexplained.org/r/start-blog/) by David Robinson on why it's a good idea for aspiring data scientists but many of the reason hold outside of data science. If you think starting a blog to just share information is a lame idea, you can read [this post](https://davidjohnbaker.rbind.io/post/blog-on-blogs/) I did on my personal website after talking about this with one of my former students.

The executive summary of that (notice I didn't say abstract) is having this presence allows you to communicate with the community you want to enter. It shows ahead of time how you think about problems. It can also catch the eye of people in the industry you want to work in. 

For example, maybe you want to stay in the world of music and not do "data science" but try to get on the ever growing data train for arts management. If you can show what you can do by showing how you take some publicly available data and turn it into a meaningful narrative, you’re going to stick out much more in both processes of networking to show your value which will eventually get you hired. 

## Get Better at Programming

The last thing that I would be remiss not to mention, especially for those doing any sort of quantitative related research is to get better at coding. 

What blows my mind is the amount of people who learn all these super-out-there stats for getting their research published, but do not put in the time (especially given the freedom you have in grad school) to teach yourself some sort of open source programming language. Arguments for open and reproducible science aside, coding will open up more doors for you in terms of career and salary than anything else right now on the market coming from academia. 

It's a bit of a pain to learn in some ways, but one of the reasons it pays so well is because it is hard to learn. But if you are no longer limited by what software is in front of you (or what your company can afford…) then your value will increase not only in the near future, but I am sure it will carve out a great trajectory for you over the next twenty years.

I feel confident in passing on this advice to the SysMus crowd in particular because in doing a graduate research degree, this process of just getting good at asking meaningful questions is the thing that is way more difficult to teach and get better at in a workplace setting. Now working with a lot of people who are aspiring data scientists, I have seen time and time again that just like practicing an instrument, you will get better at coding by just practicing it daily. 

In your current capacity as a graduate student, the way to work on this is to slowly move your projects to something like R or Python, and to try to make those projects available for people to see on Github or the Open Science Framework. Just learning how to document them well and work in a code based environment is an extremely good investment for the next 30 years of your working career (assuming median age of most SysMus readers is a little less than 30). Doing this and posting it will show to future colleagues and employers that you are going to be a colleague who is useful and easy to collaborate with.

If you’re totally new to this, the way I would suggest going forward is to first make your way through [R for Data Science](https://r4ds.had.co.nz/) , then read [Hands on Programming with R]( https://rstudio-education.github.io/hopr/) , then slowly try your hand at easy coding problems on websites like [r/daily programming challenge](https://www.reddit.com/r/dailyprogrammer/) , [daily coding problem](https://www.dailycodingproblem.com/ )  or [code wars](https://www.codewars.com/). 

When going through daily challenges, try to think of each one as a little brain teaser.  They’re just like nerdy crosswords or sudoku. It’s OK to look at the answers if you don’t get it after a couple of minutes, remember the point is to learn new ways of thinking and coding, not test the limits of your patience. Of course programming languages are not spoken languages and you also need to remember that when you are starting out, you need to build up a lot of vocabulary and see what a language can do before you can expect yourself to just look at a blank page and start typing code like some sort of hacker. Just look at a lot of code at first, the writing will come soon enough. 

In terms of what languages to learn, it really depends what you want to do, but you can’t go wrong with R, SQL, and Python. If you work in anything quant related, you have to learn SQL. Everyone does SQL. Then maybe pick either R or Python. I suggest R here (and above) because it’s way more common where you currently are as grad student in systematic musicology where you can get help from peers. Don’t make things harder for yourself. You can learn other coding languages later. There are tons of articles on the internet differentiating why you might start with one or the other, but I’d suggest picking the one that you will find most useful right now for what you’re doing as a grad student. 

I would also suggest slowly making your way through [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf) if you are remotely interested in data science. There are also data science equivalents to the [daily coding challenges](https://datascienceprep.com/).  Note that in the data science world it’s wise to learn both Python and R, but if you’re getting to that point and want resources on all this, please just get in touch with me personally and hopefully by then I will have some more resources to point you towards. You don’t have to do it all at once. 

If you need further incentive, I suggest checking out the most [recent stack overflow calculator]( https://stackoverflow.com/jobs/salary ) and just putting in one year of R or Python in combination with a doctoral degree. 

## Why?

Now you don't have to take my advice here and the advice provided is not exhaustive at all. But if you are in the middle of your PhD and are reading this, I would argue that you have nothing to lose and everything to gain from doing a little bit of industry investment each week as a graduate student. If you say you don't have time, you’re probably taking a very parochial view  of what your career and life could be by putting all your eggs in the proverbial academic basket. This is not a smart move on either personal or professional note (you never know when life is just going to happen). 

If you start to build this side of your professional development, you’ll get a couple of things. I think the most valuable thing you will gain is the peace of mind that when you are done with the monumental task that is doing a PhD, you will have some options waiting for you. By investing in these skills you will open up more avenues in your own research and will further aid your ability to pursue the questions that got you into academia in the first place. Lastly, by just trying to meet more people outside the Ivory Tower, you’ll meet more friends than you would have otherwise. 

Winding this post down I want to reflect on a talk that I also heard David Huron give at the Society for Music Theory in Vancouver the during the second year of my PhD where he predicted that a lot of the research that will capture the public's attention in the realm of music (broadly defined) will come from the world of music industry where they have [endless amounts of data](https://www.nature.com/articles/s41562-018-0508-z) and he predicted that the category divide between academia and industry will only become more important to be able to walk back and forth between the two. Now I don’t think the most important questions will be asked at this intersection, but it’s something to consider.  

Why do I think this is important to note? Well it’s worth saying out loud that even if you don't go on to an academic job, research still happens outside the Ivory Tower. There's a big demand for the skills you are cultivating as a graduate student. You have a lot more value than you think at this point.

Of course this might not be as idyllic as the past few paragraphs have made some parts of working an industry job sound. There’s a lot less time to work on things that are uniquely yours. How you spend your time is at the discretion of your boss and the needs of the company. If you want to work on your own stuff you have to do it on your own time. But the flip side of that argument is that you actually have your own time. 

Right now in my current role I am finding it a bit frustrating to work on a few of my pet projects, but again this comes in exchange for a job with a salary that reflects the years of training I have put in, a healthcare plan,  the right to not have to “take my work home with me” after the end of the day, and peace of mind that now knowing how the industry works.

This has been quite the essay, but hopefully it's explored a space that I know I wish I would have heard more about when I was a PhD student. Please feel free to reach out to me if you’d like to talk more about this! 
